//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApp.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class Table1
    {
        public int id { get; set; }
        public string name { get; set; }
        public Nullable<int> age { get; set; }
    }
}
